//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rkrApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Classes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Classes()
        {
            this.Students = new HashSet<Students>();
        }

        [Display(Name = "Класс:")]
        public int id { get; set; }

        [Display(Name = "Буква класса:")]
        public string letter { get; set; }

        [Display(Name = "Предмет:")]
        public int id_subject_number { get; set; }

        [Display(Name = "Школа:")]
        public int id_school { get; set; }

        [Display(Name = "Количество учащихся (списочный состав):")]
        public Nullable<int> count { get; set; }

        public virtual Subjects_Numbers Subjects_Numbers { get; set; }
        public virtual Schools Schools { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students> Students { get; set; }
    }
}
