//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rkrApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rkrDBEntities : DbContext
    {
        public rkrDBEntities()
            : base("name=rkrDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Areas_Check> Areas_Check { get; set; }
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<Districts> Districts { get; set; }
        public virtual DbSet<Districts_Check> Districts_Check { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Places> Places { get; set; }
        public virtual DbSet<Results> Results { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Schools> Schools { get; set; }
        public virtual DbSet<Schools_Observers> Schools_Observers { get; set; }
        public virtual DbSet<Sessions> Sessions { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Subjects_Numbers> Subjects_Numbers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Time_X> Time_X { get; set; }
        public virtual DbSet<Types_Document> Types_Document { get; set; }
        public virtual DbSet<Types_edu> Types_edu { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
