//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rkrApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    public partial class Schools
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schools()
        {
            this.Classes = new HashSet<Classes>();
            this.Schools_Observers = new HashSet<Schools_Observers>();
        }
    
        public int id { get; set; }
        [Display(Name = "Наименование:")]
        public string name { get; set; }
        public int id_district { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_type_edy { get; set; }
        public Nullable<int> id_place { get; set; }
        public string code { get; set; }

        public int getAllCountPupils()
        {
            rkrDBEntities db = new rkrDBEntities();
            int e = Convert.ToInt32(db.Classes.Where(p=> p.id_school == this.id).Sum(p=>p.count));
            return e;
        }

        public int getCountPupils()
        {
            rkrDBEntities db = new rkrDBEntities();
            int e = db.Students.Count(p => p.Classes.id_school == this.id);
            return e;
        }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classes> Classes { get; set; }
        public virtual Districts Districts { get; set; }
        public virtual Places Places { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schools_Observers> Schools_Observers { get; set; }
        public virtual Types_edu Types_edu { get; set; }
        public virtual Users Users { get; set; }
    }
}
