//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rkrApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Areas_Check
    {
        public int id { get; set; }
        public int id_user_check { get; set; }
        public int id_subject_number { get; set; }
        public int id_area { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Subjects_Numbers Subjects_Numbers { get; set; }
        public virtual Users Users { get; set; }
    }
}
