//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rkrApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Districts_Check
    {
        public int id { get; set; }
        public int id_user_check { get; set; }
        public int id_subject_number { get; set; }
        public int id_district { get; set; }
        public List<Results> CreateResults(int first_id_result)
        {
            List<Results> listResults = new List<Results>();
            ICollection<Schools> listSchools = this.Districts.Schools;
            foreach (Schools school in listSchools)
            {
                ICollection<Classes> listClasses = school.Classes;
                foreach (Classes _class in listClasses)
                    if (_class.id_subject_number == this.id_subject_number)
                    {
                        ICollection<Students> listStudents = _class.Students;
                        foreach (Students student in listStudents)
                        {
                            if (student.scan != null && student.Results.Where(r => r.number_verification == 1).Count() == 0)
                            {
                                Results result = new Results();
                                result.id = first_id_result;
                                result.id_student = student.id;
                                result.id_user = this.id_user_check;
                                result.number_verification = 1;
                                listResults.Add(result);
                                first_id_result++;
                            }
                        }
                    }
            }
            return listResults;
        }

        public virtual Districts Districts { get; set; }
        public virtual Subjects_Numbers Subjects_Numbers { get; set; }
        public virtual Users Users { get; set; }
    }
}
