//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rkrApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int id { get; set; }
        public string name { get; set; }
        public string path { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int id_subject_number { get; set; }
        public int id_type_document { get; set; }
    
        public virtual Subjects_Numbers Subjects_Numbers { get; set; }
        public virtual Types_Document Types_Document { get; set; }
    }
}
