//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rkrApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Area = new HashSet<Area>();
            this.Areas_Check = new HashSet<Areas_Check>();
            this.Districts_Check = new HashSet<Districts_Check>();
            this.Results = new HashSet<Results>();
            this.Schools = new HashSet<Schools>();
            this.Schools_Observers = new HashSet<Schools_Observers>();
            this.Sessions = new HashSet<Sessions>();
        }

        [Display(Name = "Пользователь:")]
        public int id { get; set; }

        [Display(Name = "Пароль:")]
        public string password { get; set; }

        [Display(Name = "email:")]
        [Required]
        public string email { get; set; }

        [Display(Name = "Роль:")]
        [Required]
        public int id_role { get; set; }

        [Display(Name = "Фамилия:")]
        [Required]
        public string surname { get; set; }

        [Display(Name = "Имя:")]
        [Required]
        public string name { get; set; }

        [Display(Name = "Отчество:")]
        public string patronymic { get; set; }

        public String getArea()
        {
            rkrDBEntities db = new rkrDBEntities();
            if (this.id_role == 1 || this.id_role == 2)
            {
                return "";
            }
            else if (this.id_role == 3)
            {
                return db.Schools.FirstOrDefault(p => p.id_user == this.id).Districts.Area.name;
            }
            else if (this.id_role == 4)
            {
                return db.Schools_Observers.FirstOrDefault(p => p.id_observer == this.id).Schools.Districts.Area.name;
            }
            else if (this.id_role == 5)
            {
                return db.Districts_Check.FirstOrDefault(p => p.id_user_check == this.id).Districts.Area.name;
            }
            else if (this.id_role == 6)
            {
                return db.Areas_Check.FirstOrDefault(p => p.id_user_check == this.id).Area.name;
            }
            else
            {
                return db.Area.FirstOrDefault(p => p.id_coordinator == this.id).name;
            }
        }

        public String getDistrict()
        {
            rkrDBEntities db = new rkrDBEntities();
            if (this.id_role == 3)
            {
                return db.Schools.FirstOrDefault(p => p.id_user == this.id).Districts.name;
            }
            else if (this.id_role == 4)
            {
                return db.Schools_Observers.FirstOrDefault(p => p.id_observer == this.id).Schools.Districts.name;
            }
            else if (this.id_role == 5)
            {
                return db.Districts_Check.FirstOrDefault(p => p.id_user_check == this.id).Districts.name;
            }
            else
            {
                return "";
            }
        }


        public String getSchool()
        {
            rkrDBEntities db = new rkrDBEntities();
            if (this.id_role == 3)
            {
                return db.Schools.FirstOrDefault(p => p.id_user == this.id).name;
            }
            else if (this.id_role == 4)
            {
                return db.Schools_Observers.FirstOrDefault(p => p.id_observer == this.id).Schools.name;
            }
            else
            {
                return "";
            }
        }

        public String getSubject()
        {
            rkrDBEntities db = new rkrDBEntities();
            if (this.id_role == 1 || this.id_role == 2 || this.id_role == 3 || this.id_role == 4 || this.id_role == 7)
            {
                return "";
            }
            else if(this.id_role == 5)
            {
                return db.Districts_Check.FirstOrDefault(p => p.id_user_check == this.id).Subjects_Numbers.subject;
            }
            else 
            {
                return db.Areas_Check.FirstOrDefault(p => p.id_user_check == this.id).Subjects_Numbers.subject;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Area> Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Areas_Check> Areas_Check { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Districts_Check> Districts_Check { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Results> Results { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schools> Schools { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schools_Observers> Schools_Observers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sessions> Sessions { get; set; }
    }
}
